create table Users(
    id INT UNIQUE PRIMARY KEY,
    username varchar(255),
    password varchar(255),
    full_name varchar(255),
    email varchar(255),
    phone varchar(10),
    status BIT,
    create_at date
);

create table Roles(
    id INT PRIMARY KEY,
    name varchar(255),
    description varchar(255)
);

create table UserRole(
    id INT PRIMARY KEY,
    user_id int,
    role_id int,
    assigned_at date,
    expired_at date,
    FOREIGN KEY (user_id) REFERENCES Users(id),
    FOREIGN KEY (role_id) REFERENCES Roles(id)
);

insert into Roles(name,description) values ('ADMIN','Manage the whole system');
insert into Roles(name,description) values('STAFF','Coworker');
insert into Roles(name,description) values('MANAGE','Manage the staff and system');

ALTER TABLE Roles
    ALTER COLUMN id
        ADD GENERATED BY DEFAULT AS IDENTITY;

delete from UserRole where id=5